# Generated by Django 6.1 on 2026-08-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='applied_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
    ]
