# Generated by Django 6.1 on 2026-08-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_remove_job_applied_date_remove_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applied_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
